# Generated by Django 4.2.13 on 2024-05-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odbor',
            name='nazov',
            field=models.CharField(max_length=80),
        ),
    ]
