# Generated by Django 4.2.13 on 2024-05-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0003_dostupnost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dostupnost',
            name='nazov',
            field=models.CharField(max_length=25),
        ),
    ]
